FROM golang:1.7
RUN apt-get update && \
    apt-get install -y build-essential && \
    curl glide.sh/get | sh
COPY . $GOPATH/src/github.com/cpg1111/pr-show-metrics-pipeline/
WORKDIR $GOPATH/src/github.com/cpg1111/pr-show-metrics-pipeline
ENTRYPOINT ["make"]
